// <auto-generated />
using System;
using BudgetTracker.DAL.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BudgetTracker.Migrations
{
    [DbContext(typeof(BudgetTrackerContext))]
    partial class BudgetTrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BudgetTracker.Models.CategoryData", b =>
                {
                    b.Property<int>("CategoryDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Bill")
                        .HasColumnType("boolean");

                    b.Property<bool>("Entertainment")
                        .HasColumnType("boolean");

                    b.Property<bool>("Food")
                        .HasColumnType("boolean");

                    b.Property<bool>("Grocery")
                        .HasColumnType("boolean");

                    b.Property<bool>("Health")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Other")
                        .HasColumnType("boolean");

                    b.Property<bool>("Transportation")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryDataId");

                    b.ToTable("CategoryData");
                });

            modelBuilder.Entity("BudgetTracker.Models.CategoryExpense", b =>
                {
                    b.Property<int>("CategoryExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("AmountLeft")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AmountSpent")
                        .HasColumnType("numeric");

                    b.Property<int>("CategoryTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EffectiveEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EffectiveStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastModifiedTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("LowerBudgetAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("MonthExpenditureId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UpperBudgetAmount")
                        .HasColumnType("numeric");

                    b.HasKey("CategoryExpenseId");

                    b.ToTable("CategoryExpenses");
                });

            modelBuilder.Entity("BudgetTracker.Models.MonthExpenditure", b =>
                {
                    b.Property<int>("MonthExpenditureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MonthExpenditureId");

                    b.ToTable("MonthExpenditures");
                });

            modelBuilder.Entity("BudgetTracker.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CategoryExpenseId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastModifiedTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MonthExpenditureId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BudgetTracker.Models.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModifiedTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
